CREATE TABLE SCAN (
    SCAN_ID       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROCESS_ID    LONG,
    HOST_NAME     VARCHAR(63),
    USER_NAME     VARCHAR(63),
    ROOT          VARCHAR(512) NOT NULL,
    STARTED       TIMESTAMP,
    FINISHED      TIMESTAMP
)

CREATE TABLE FILE (
    FILE_ID           BIGINT PRIMARY KEY,
    DIR_ID            BIGINT,
    SCAN_ID           BIGINT NULL,
    PATH              VARCHAR(512) NOT NULL,
    NAME              VARCHAR(512) NOT NULL,
    SIZE              BIGINT,
    LAST_WRITE_ACCESS TIMESTAMP NOT NULL,
    CHECKSUM          VARBINARY(32) DEFAULT X'0000000000000000000000000000000000000000000000000000000000000000',
    CALC_STARTED      TIMESTAMP,
    CALC_FINISHED     TIMESTAMP
)


--          "ALTER TABLE FILE ADD FOREIGN KEY (DIR_ID) REFERENCES FILE (FILE_ID) ON DELETE CASCADE
ALTER TABLE FILE ADD FOREIGN KEY (SCAN_ID) REFERENCES SCAN (SCAN_ID) ON DELETE CASCADE

CREATE UNIQUE INDEX SCAN_ID_DIR_ID_NAME ON FILE (SCAN_ID, DIR_ID, NAME)

CREATE INDEX NAME ON FILE (NAME)

CREATE INDEX SIZE ON FILE (SIZE)

CREATE INDEX LAST_WRITE_ACCESS ON FILE (LAST_WRITE_ACCESS)

CREATE INDEX CHECKSUM ON FILE (CHECKSUM)

CREATE INDEX SIZE_NAME ON FILE (SIZE, NAME)

CREATE INDEX EQUAL ON FILE (SIZE, NAME, CHECKSUM)

CREATE VIEW SCAN_STAT AS (
    SELECT SCAN.SCAN_ID SCAN_ID, ROOT, STARTED, FINISHED,
    SUM(SIZE) AS SIZE,
        SUM(CASE WHEN SIZE IS NULL THEN 1 ELSE 0 END) AS DIR_COUNT,
        COUNT(SIZE) AS FILE_COUNT,
        MIN(LAST_WRITE_ACCESS) AS MIN_LAST_WRITE_ACCESS, 
        MAX(LAST_WRITE_ACCESS) AS MAX_LAST_WRITE_ACCESS,
        COUNT(DISTINCT 
            CASE WHEN CHECKSUM = X'0000000000000000000000000000000000000000000000000000000000000000'
                      OR CHECKSUM = X'00' THEN NULL ELSE CHECKSUM END
        ) AS CHECKSUM_COUNT_DISTINCT,
        COUNT(
            CASE WHEN CHECKSUM = X'0000000000000000000000000000000000000000000000000000000000000000'
                      OR CHECKSUM = X'00' THEN NULL ELSE CHECKSUM END
        ) AS CHECKSUM_COUNT_ALL,
        MIN(CALC_STARTED) AS FIRST_CHECKSUM_FINISHED,
        MAX(CALC_FINISHED) AS LAST_CHECKSUM_FINISHED
    FROM SCAN
    JOIN FILE
        ON (SCAN.SCAN_ID = FILE.SCAN_ID)
    GROUP BY SCAN.SCAN_ID, ROOT, STARTED, FINISHED
)
