CREATE LOCAL TEMPORARY TABLE FILE_DUPLICATE AS
SELECT FILE_ID
FROM FILE
         JOIN (SELECT NAME, SIZE
               FROM FILE
               GROUP BY SIZE, NAME
               HAVING SIZE IS NOT NULL
                  AND COUNT(*) > 1) DUPLICATES
              ON FILE.NAME = DUPLICATES.NAME AND FILE.SIZE = DUPLICATES.SIZE
