CREATE LOCAL TEMPORARY TABLE DUPLICATE_CANDIDATE AS
SELECT FILE_ID
FROM FILE
         JOIN (SELECT NAME, SIZE
               FROM FILE
               WHERE IS_DIR = FALSE
               GROUP BY SIZE, NAME
               HAVING COUNT(*) > 1) DUPLICATE
              ON FILE.NAME = DUPLICATE.NAME AND FILE.SIZE = DUPLICATE.SIZE
