UPDATE file DirToUpdate
SET (SIZE, FILES_CONTAINED, DIRS_CONTAINED) = (0, 0, 0)
WHERE DirToUpdate.SIZE IS NULL AND DirToUpdate.IS_DIR = TRUE AND DirToUpdate.SCAN_ID = ?
  AND DirToUpdate.FILE_ID NOT IN (
    SELECT File.DIR_ID
    FROM FILE File
    WHERE File.DIR_ID = DirToUpdate.FILE_ID
    GROUP BY File.DIR_ID
)