UPDATE FILE DirToUpdate
SET CHECKSUM = (
    SELECT COALESCE(CAST(HASH('SHA-256', LISTAGG(
            rawtohex(FileInDir.CHECKSUM)
        , '') WITHIN GROUP (ORDER BY FileInDir.NAME)) as varbinary(32)
           ), X'0000000000000000000000000000000000000000000000000000000000000000') CHECKSUM
    FROM FILE Dir
             LEFT OUTER JOIN FILE FileInDir
                             ON Dir.FILE_ID = FileInDir.DIR_ID
    WHERE Dir.FILE_ID= DirToUpdate.FILE_ID
    GROUP BY Dir.FILE_ID
    HAVING COUNT(FileInDir.DIR_ID) = COUNT(FileInDir.CHECKSUM) OR COUNT(*) = 0
    )
WHERE DirToUpdate.FILE_ID IN (
    SELECT Dir.FILE_ID
    FROM FILE Dir
    LEFT OUTER JOIN FILE FileInDir
        ON Dir.FILE_ID = FileInDir.DIR_ID
    WHERE ARRAY_CONTAINS(?, Dir.SCAN_ID) AND
          Dir.IS_DIR = TRUE AND Dir.CHECKSUM IS NULL
    GROUP BY Dir.FILE_ID
    HAVING COUNT(FileInDir.DIR_ID) = COUNT(FileInDir.CHECKSUM) OR COUNT(*) = 0
    )
